name: SpectatorRotator
main: de.crafttogether.spectatorrotator.SpectatorRotator
version: 1.6.0
website: http://www.craft-together.de
author: J0schlZ
description: Spectate your players
commands:
   spectate:
     aliases: [spec, rspec, rspectate]
     description: Toggle SpectatorRotator
     usage: /spectate [radius] [-noclip]