name: SpectatorRotator
main: de.crafttogether.SpectatorRotator
version: 1.4.0
website: http://www.craft-together.de
author: J0schlZ
description: Spectate your players
commands:
   spectate:
     description: Toggle SpectatorRotator
     usage: /spectate